### ISSUE TITLE
Account View

### ISSUE THREAD

**Issue by kckthx** [OpenArchive/openarchive-ios#10]
The account view is accessed from the avatar in the top left. From there you can set up your profile, connect to a private server, internet archive (later), and add projects or browse existing projects tied to a server. Individual flows are packaged and pasted below. Camera icon is attached below as well. 

![oa-accountview](https://user-images.githubusercontent.com/36669955/49410688-7c8bef00-f72b-11e8-9fba-8d18618d77fd.png)

[AccountIcons.zip](https://github.com/OpenArchive/openarchive-ios/files/2641914/AccountIcons.zip)
[v_AddProjectNoServer.zip](https://github.com/OpenArchive/openarchive-ios/files/2645171/v_AddProjectNoServer.zip)
[v_AddProjectServer.zip](https://github.com/OpenArchive/openarchive-ios/files/2645172/v_AddProjectServer.zip)
[v_AddServerFromAccount.zip](https://github.com/OpenArchive/openarchive-ios/files/2645173/v_AddServerFromAccount.zip)
[v_SetUpProfile.zip](https://github.com/OpenArchive/openarchive-ios/files/2645174/v_SetUpProfile.zip)

**Comment by tladesignz** [comment]
So, a "project" is the first directory level on a WebDAV server target?

Should you be able to descend into the directory structure?

**Comment by n8fr8** [comment]
I think that we should not impose a specific structure, but just allow them to choose the folder they want to use as their project base. Thus, we have to implement a general folder browser/selector.

HOWEVER, in the short term, just showing the base layer of directories / folders would be acceptable.

**Comment by tladesignz** [comment]
See #8

**Comment by n8fr8** [comment]
We've agreed that in account config, the user will provide a base folder, and we will default to "openarchive" for now as the base folder.

**Comment by tladesignz** [comment]
@kckthx, is the empty avatar image somewhere? You provided the small photo, but the empty avatar is not in the attachments. Please point me to it or attach it here. SVG is great!

**Comment by kckthx** [comment]
right, @tladesignz here you go! 
[avatar-empty.svg.zip](https://github.com/OpenArchive/openarchive-ios/files/2766217/avatar-empty.svg.zip)

**Comment by tladesignz** [comment]
@kckthx Did you provide icons used in the file browser somewhere?

**Comment by kckthx** [comment]
@tladesignz sorry, which icons?

**Comment by tladesignz** [comment]
@kckthx the folder icon used in the "Browse Projects" scene.

**Comment by kckthx** [comment]
[browse-folder.svg.zip](https://github.com/OpenArchive/openarchive-ios/files/2796584/browse-folder.svg.zip)
@tladesignz  here you go

**Comment by tladesignz** [comment]
Basically implemented. Superseded by #35. Progress will be tracked there.
