### ISSUE TITLE
if uploaded to archive.org, have option to share public link

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/openarchive-ios#102]
this is based on the OpenArchive Android 1.0 feature for public sharing

**Comment by tladesignz** [comment]
I already had that in my first shot, but with the new design, I don't know where to put it.
Would need UI proposal.

**Comment by foundscapes** [comment]
@kckthx how's this going?

**Comment by tladesignz** [comment]
I added it as another infobox above the "people" description, when available.
Could use an icon, though.

**Comment by foundscapes** [comment]
Yes, we need a share icon, can you find the right one without OKThanks' help @tladesignz? If not, send me the parameters/size and I'll find one.

**Comment by foundscapes** [comment]
Also, I didn't see this infobox in the edit scene

**Comment by tladesignz** [comment]
> Also, I didn't see this infobox in the edit scene

Released latest TestFlight just now.

> Yes, we need a share icon, can you find the right one without OKThanks' help @tladesignz?

I'll try to find something nice looking. If I can't find anything suitable, I'll get back!

**Comment by foundscapes** [comment]
> > Also, I didn't see this infobox in the edit scene
> 
> Released latest TestFlight just now.
> 
> > Yes, we need a share icon, can you find the right one without OKThanks' help @tladesignz?
> 
> I'll try to find something nice looking. If I can't find anything suitable, I'll get back!

Great, thank you!
