### ISSUE TITLE
Preview View --Update

### ISSUE THREAD

**Issue by kckthx** [OpenArchive/openarchive-ios#107]
Workflows for the preview view editing before and after upload
@foundscapes @tladesignz @cstiens 

![Single Image View_Edit Info](https://user-images.githubusercontent.com/36669955/57802363-63945a80-771b-11e9-8614-0a8b821fb2cc.jpg)

**Comment by tladesignz** [comment]
@kckthx What's the color code for the red?
Is the flag now red, everywhere?

**Comment by tladesignz** [comment]
And what's the flag description, now?
"SIGNIFICANT CONTENT" or "SENSITIVE CONTENT"?

**Comment by cstiens** [comment]
It's 'Significant content'

**Comment by kckthx** [comment]
@tladesignz when an image has been flagged, the icon will show as this yellow (sorry I updated the designs but forgot to update the workflow.) So everywhere it shows red in that flow, it will actually be yellow (#E9BD07)
![yellow-flag](https://user-images.githubusercontent.com/36669955/57932393-707e8e80-7880-11e9-9f6b-8f0071e8d7b8.png)
