### ISSUE TITLE
Revisiting UI Tweaks

### ISSUE THREAD

**Issue by kckthx** [OpenArchive/openarchive-ios#109]
@tladesignz these are some fine tuning of UI that I've noticed throughout the app. Mainly consisiting of 

* fonts (https://fonts.google.com/specimen/Montserrat?selection.family=Montserrat)
* text alignment in fields
* a line under the bottom of last fields

![UI Tweaks](https://user-images.githubusercontent.com/36669955/57957219-2d90db00-78c1-11e9-87b9-de19650d4624.jpg)

**Comment by foundscapes** [comment]
@tladesignz Please include font updates too for these and also #108 - thank you!

**Comment by tladesignz** [comment]
Sorry, the "x" clear button isn't available. That's a drawback of that Eureka form library, I'm using here.
If you want that hard, I need to rework that scene, but that needs to wait until after my vacation.
Could be done in conjunction with #108.
