### ISSUE TITLE
After returning from preview, connect menu is shown

### ISSUE THREAD

**Issue by tladesignz** [OpenArchive/openarchive-ios#111]
Can't skip it, but when app is restarted, everything is fine again.

Reproduce:
- fresh install
- connect to nextcloud
- create 2 projects
- add 3 images to the first project
- add 3 images to the second project
-> jumps to preview
-> select back
-> connect scene

**Comment by foundscapes** [comment]
Possibly caused by location servers since it happens in picker. Let's remove auto-load location and try to reproduce @tladesignz

**Comment by tladesignz** [comment]
> Possibly caused by location servers since it happens in picker. Let's remove auto-load location and try to reproduce @tladesignz 

That was the wrong issue to comment. I opened a separate one for this: #112
