### ISSUE TITLE
Internet Archive UI 

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/openarchive-ios#114]
- complex login process
- unable to upload media
- crashes

**Comment by tladesignz** [comment]
Just tested this and I'm actually surprised how good it works, considering that I didn't touch that code it in months while rearranging everything else around it.

So, I didn't experience any crash nor any error, besides expected ones, when I messed up the credentials.

Can you please describe in detail, what you did to have this negative outcome?

**Comment by n8fr8** [comment]
I need to check if the simple login / scraping is still possible, as the code stopped work on OA Android

**Comment by foundscapes** [comment]
Perhaps there is UI to help guide people through it better - popup? 
provide login page and scrape keys from there?

**Comment by n8fr8** [comment]
Login through webview and scrape this page: https://archive.org/account/s3.php

**Comment by tladesignz** [comment]
@foundscapes, @kckthx  I did a first stab at this. I'm pretty sure, you come up with a better UI! I'll do a build now, close this and remove myself from it until you decided on an improved UI. Have fun! ;-) Reopen, when you have a new UI/UX design!

**Comment by kckthx** [comment]
Alrighty folks, I whipped up a little UI. 
![_upload to internet archive_v1](https://user-images.githubusercontent.com/36669955/61313524-38cc8e00-a7c0-11e9-9e1c-064e3393c20f.jpg)
