### ISSUE TITLE
Delete message is unclear if item removed from server

### ISSUE THREAD

**Issue by seamustuohy** [OpenArchive/openarchive-ios#119]
The iOS notice provided when an item is deleted from a users phone is "This item will be removed from your project." This is ambiguous as to whether the item is just deleted from your phone, or also deleted on the server.  Deleting an item did not remove it from the server in my testing. It looks as if this simply clears the copy of the image stored locally by Save. (The uploaded image is not removed from the users photos. 

<img width="200" alt="open_archive_save_notice" src="https://user-images.githubusercontent.com/1226247/59597863-d1d88e00-90c8-11e9-874b-b249aa11713f.png">

Two failure cases you don't want when they delete an item using this menu: 
1. User thinks they have deleted something from the server;
2.  User thinks they have deleted the original item.

I'd recommend providing a clearer alert message that lets a user know what exactly Save is doing. I'd propose something like this: "Remove this status message from Save and delete Save's local copy of the media."

**Comment by tladesignz** [comment]
@cstiens, @kckthx or @foundscapes: please provide new wording if desired.

**Comment by foundscapes** [comment]
Remove Media from Save
This item will be removed only from the Save App. 
It will remain on the server and in your camera roll.


How's that @tladesignz @seamustuohy

**Comment by tladesignz** [comment]
I stumbled over this while going through my email. Nathan moved it back, but it's such a small change, I promoted it to the current dev sprint. :-)
