### ISSUE TITLE
Add Project from Home

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#12]
Mockups coming..

The workflow for adding a project from the 'Account' view is in ticket #10 
![00_oa-add-project-from-home](https://user-images.githubusercontent.com/36669955/49610183-6ec0ae80-f963-11e8-80cd-96439d8c8933.png)

**Comment by n8fr8** [comment]
No "All" tab. There is always a Project.

**Comment by tladesignz** [comment]
Most of the stuff shown in the design image is implemented.
Further refinements are tracked in #36, #37.
