### ISSUE TITLE
Projects not deleting after clicking "remove from app"

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/openarchive-ios#122]
It was not delete from either the Server/Project Screen here: 
![IMG_2480](https://user-images.githubusercontent.com/2231711/60053198-1dbca180-968c-11e9-86d0-088a949637e2.PNG) or in the projects view here: 
![IMG_2479](https://user-images.githubusercontent.com/2231711/60053211-27460980-968c-11e9-9055-541ebb162efd.PNG) and I definitely deleted it, as shown here: 
![IMG_2478](https://user-images.githubusercontent.com/2231711/60053229-3036db00-968c-11e9-92c3-7ae20b708e2a.PNG)

Secondary issue: you can add the same folder twice as seen with "NCTest19"

**Comment by foundscapes** [comment]
@tladesignz why did you reassign to us? I think this was a bug....

**Comment by tladesignz** [comment]
Because this is no for testing. That's how we do it since Nathan created the "for testing" label.
