### ISSUE TITLE
Don't allow multiple projects with the same name

### ISSUE THREAD

**Issue by tladesignz** [OpenArchive/openarchive-ios#124]
Raised in #122.

**Comment by tladesignz** [comment]
Please advise on wording, if you don't like it.

**Comment by foundscapes** [comment]
There weren't two projects with the same name, it just added the same project twice and then when I tried deleting one, it wouldn't. As mentioned in #122

**Comment by tladesignz** [comment]
Trust me, they were 2 different projects. It's just, that they had the same name. Projects in Save are identified by a UUID, not their names.

**Comment by foundscapes** [comment]
These are not two projects. It is the same project folder from the server, as you can see. 
![IMG_2490](https://user-images.githubusercontent.com/2231711/60133729-c9302980-9752-11e9-9f34-aad0bc1d5b90.PNG)

**Comment by tladesignz** [comment]
Clarified during meeting.
