### ISSUE TITLE
Add upload progress to files in upload scene

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/openarchive-ios#128]
Have (Total) MB - ↑x MB (uploaded) to indicate status
See last row on this image for UI

![IMG_2731](https://user-images.githubusercontent.com/2231711/60541894-66e1a680-9cc7-11e9-86ad-5eefd0ad6dbd.PNG)

**Comment by tladesignz** [comment]
Note: This will be in a TestFlight *after* build 29.
