### ISSUE TITLE
Add Info

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#13]
![00_oa-add-details](https://user-images.githubusercontent.com/36669955/49612481-7899e000-f96a-11e8-8ecb-c799df91dc3d.png)

**Comment by n8fr8** [comment]
We may need to break this ticket up into smaller screens

**Comment by tladesignz** [comment]
@kckthx: Could you please provide the 3 icons which are shown in the top right corner of an asset? SVG, as usual. Thanks!

**Comment by kckthx** [comment]
@tladesignz 
[Add Info.zip](https://github.com/OpenArchive/openarchive-ios/files/2936952/Add.Info.zip)

Here you go! I also added an edit icon that we may or may not implement. But just so you have it.
![oa_add-info-fullphoto](https://user-images.githubusercontent.com/36669955/53892211-7a1e8700-3ff1-11e9-8391-d48d548bf5d1.png)

**Comment by tladesignz** [comment]
See #34 for updated designs.

**Comment by tladesignz** [comment]
@kckthx Can you provide the "x" as SVG icon, white-on-transparent? Thank you!

**Comment by kckthx** [comment]
[Cancel.svg.zip](https://github.com/OpenArchive/openarchive-ios/files/2942746/Cancel.svg.zip)

**Comment by kckthx** [comment]
@tladesignz there you go
