### ISSUE TITLE
Prepare to ship on iTunes

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/openarchive-ios#130]
To do:
- Localize (need to do this after we launch app)
- Go through apple forms
- Automate screenshot capture / resizing for app store (we choose screenshots)

**Comment by tladesignz** [comment]
Things which need preparation:
- List of scenes to screenshot and exact definition what should be seen on them:
  - Server account to use when generating screenshots
  - List of projects, images
- Fill all forms of AppStoreConnect here: https://appstoreconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/1462212414/ios/versioninfo
(Mind the language drop-down on the right!)

**Comment by tladesignz** [comment]
>  1. Projects Scene: New | 2018 Berlin | 2019 Tunis

2 Things:

1. Normally, the newer project is to the left. We can do it like this, but the more logical order would be:

New | 2019 Tunis | 2018 Berlin

2. Should the currently selected project be empty?

If not: *Provide assets*!

>  2. Preview Scene: with all uploads

I don't know what "with all uploads" should mean in that context.

Please provide assets!

>  3. Metadata editing screen

With which asset? What should be seen in the metadata? Please provide!

>  4. Upload scene with progress bars

Again: Which assets?

>  5. Uploaded just now 

Unclear. Best provide a screenshot how you want it to be.

>  6. Project Settings w/ CC licensing

Which project? Which toggles should be flagged?

>  7. Server set up scene shows IA and private webdav server 

Unclear. Do you mean the menu with 2 set up spaces or the scene where one chooses between that two before creating one?

>  8. Add project / make new

You mean the static scene where the user chooses between "Create New Project" and "Browse Existing Projects"?

**Comment by tladesignz** [comment]
@foundscapes, @n8fr8: I guess we should create a project on https://www.transifex.com/ to coordinate translations? Please coordinate about if GP or @foundscapes herself should set that up and add me such, that I can set up the Transifex command line interface to automatically grab translations.

**Comment by foundscapes** [comment]
> > 1. Projects Scene: New | 2018 Berlin | 2019 Tunis
> 
> 2 Things:
> 
>     1. Normally, the newer project is to the left. We can do it like this, but the more logical order would be:
> 
> 
> New | 2019 Tunis | 2018 Berlin

Yes, makes sense
> 
>     1. Should the currently selected project be empty?
no...it was unclear what exactly you needed for the simulator 
> 
> 
> If not: _Provide assets_!

Here you go:
> 
> > 1. Preview Scene: with all uploads
> 
> I don't know what "with all uploads" should mean in that context.

This is what I meant:
![IMG_3387](https://user-images.githubusercontent.com/2231711/61668161-c7de1800-ac90-11e9-94f3-abda7d957bcf.PNG)


> 
> Please provide assets!
> 
> > 1. Metadata editing screen
> 
> With which asset? What should be seen in the metadata? Please provide!

![IMG_3381](https://user-images.githubusercontent.com/2231711/61668206-e7754080-ac90-11e9-9b17-6dadbcc81612.PNG)

> 
> > 1. Upload scene with progress bars
> 
> Again: Which assets?
![IMG_3384](https://user-images.githubusercontent.com/2231711/61668220-f0fea880-ac90-11e9-8e5b-d6fc8265e45b.PNG)


> 
> > 1. Uploaded just now
> 
> Unclear. Best provide a screenshot how you want it to be.

![IMG_3387](https://user-images.githubusercontent.com/2231711/61668241-fbb93d80-ac90-11e9-9eed-0b3045650c5c.PNG)

> 
> > 1. Project Settings w/ CC licensing
> 
> Which project? Which toggles should be flagged?
![IMG_3448](https://user-images.githubusercontent.com/2231711/61668295-21dedd80-ac91-11e9-9ce8-5733edfb8f79.PNG)

> 
> > 1. Server set up scene shows IA and private webdav server
> 
> Unclear. Do you mean the menu with 2 set up spaces or the scene where one chooses between that two before creating one?
![IMG_3449](https://user-images.githubusercontent.com/2231711/61668341-43d86000-ac91-11e9-827b-2f5a89b1bfc5.PNG)

> 
> > 1. Add project / make new
> 
> You mean the static scene where the user chooses between "Create New Project" and "Browse Existing Projects"?
Yes
![IMG_3450](https://user-images.githubusercontent.com/2231711/61668405-69fe0000-ac91-11e9-9da0-64e97ab6cb45.PNG)

**Comment by n8fr8** [comment]
submitted to Apple for review!

**Comment by foundscapes** [comment]
I am reopening this one just so I can close it! :)

**Comment by foundscapes** [comment]
SUBMITTED TO APPLE FOR REVIEW!
