### ISSUE TITLE
Can we close the already opened projects in Save app?

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/openarchive-ios#132]
I have launched the app and opened and created several projects. But once it is opened or created, I am not able to find any close button to close the not required projects.

Is there any way or any function by which I can close the opened projects?

**Comment by tladesignz** [comment]
You can delete projects in the menu which appears when tapping the server icon or name. Swipe a project to left in the project list or tap the project and tap "Remove from App". There's no "close".
