### ISSUE TITLE
Videos not uploading on version 33 testflight for ipad

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/openarchive-ios#133]
Steps to Reproduce :

1. Launch the application in ipad
2. Select the project and click on "+" icon to add the media
3. Select the video file and click on Upload

Expected Result -
Videos should start  uploading when we click on Upload. 

Actual Result -
Videos are not uploading when we click on upload. It keeps on processing and the size of the video is shown as zero kb

Below is the screenshot

![Issue 132](https://user-images.githubusercontent.com/8190141/61168617-6fab6580-a56e-11e9-9da5-f68985b17234.jpg)

**Comment by n8fr8** [comment]
Can you provide a copy of the source video file you are trying to upload so we can try to reproduce?

**Comment by purvi-ranawat** [comment]
Closed the issue by mistake

**Comment by tladesignz** [comment]
Hm. Is it a very large video?
Files need to get imported. If it's a large video, that may take some minutes. As long as it's not fully imported, the upload won't start. The "Zero KB" file size may be an indication of that situation.

Did it upload eventually?

Maybe we need some UI improvement here, in that case.

**Comment by purvi-ranawat** [comment]
@foundscapes It is working fine on iPad air 2 build v. 2.1.0 (38)

**Comment by foundscapes** [comment]
Awesome, thank you
