### ISSUE TITLE
Can we edit info while the media is getting uploaded?

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/openarchive-ios#135]
When we first select the media and click on upload without entering any info. Then while the media is still getting uploaded, we click on Add Info and add the relevant information on the media. So, should it be allowed?

Also, currently after the media is uploaded, we are not able to edit any info. Add Info button is disabled . So, is it ok?

**Comment by tladesignz** [comment]
Nicely caught! Thanks!
