### ISSUE TITLE
Internet Archive Crash on iPhone 8

### ISSUE THREAD

**Issue by kckthx** [OpenArchive/openarchive-ios#136]
**iphone 8 12.3.1**
When I connected to internet archive, it worked. I created a new project and imported media. When I tapped “upload” it crashed.
    * When I reopened the app, the media was still in a queue as it should be. I tapped “NEXT” and it uploaded without crashing.
    *  _I did the same thing on an iphone6 12.3.1 and it worked — did NOT crash._

I reproduced this a couple times and it still happened

@tladesignz @foundscapes

**Comment by kckthx** [comment]
I just killed the app, reopened and tried again to upload images to the same project in internet archive on my iPhone 8 from the share sheet and it crashed before they even imported. When I try to reopen the app it immediately crashes.

I also recreated for the third time on the iphone 6 and it crashed like the 8 did in this comment -- did it a fourth time and it has been working ever since.

**Comment by kckthx** [comment]
except now it also crashing every time I try to open it, just like the 8 :)

**Comment by purvi-ranawat** [comment]
For me , on Iphone XR, when I open the app then remain inactive for 2 mins and then try to Archieve project, the app crashes

**Comment by tladesignz** [comment]
I'm sorry, but there must be something, which is in some way special compared to what I am doing or compared to the situation I have on my phone. To find that important difference, please do the following:

- Make sure, you are running the latest version (currently build 33) and it is a *fresh* install. Don't do updates. Data structures changed over versions and are incompatible to each other. (Sorry, but maintaining compatibility is time consuming and keeps legacy code around which is nothing we want before the first public release.)

- Attach the crashlog to a bug report. Here is a guide where to find it: https://help.dayoneapp.com/en/articles/440759-getting-ios-crash-logs
(Don't send to dayone, of course!)
Make sure, the crash report is the one which reflects the crash you are reporting on!
The apps name in the report list should be "OpenArchive".

- Please describe as precisely the circumstances:
  - Device type and OS version, language set
  - Config used in the app (which server? Used WiFi or LGE?)
  - Description of files used (Type? Length/size?)
  - As precise as possible description of what you did. Which steps in what order? Did you background the app or switched off the device? How long was the app suspended?

**Comment by purvi-ranawat** [comment]
@foundscapes I'm unable to reproduce it on version 38 on iphone XR
