### ISSUE TITLE
Need more specific error message for Login issue

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/openarchive-ios#138]
This error was caused when I entered an incorrect password. Please make an error for this that reads: Incorrect Password 

(or if you can't tell if it's login/pw on your end): Incorrect Login or Password

![signal-2019-07-17-092503](https://user-images.githubusercontent.com/2231711/61396605-f026da80-a87c-11e9-99c7-b6c056c0f6f2.png)

**Comment by tladesignz** [comment]
Will be fixed in build 34.

**Comment by foundscapes** [comment]
Also please add error on upload
