### ISSUE TITLE
Can we upload audio files too to the Save App on IOS?

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/openarchive-ios#140]
In Save FAQ on open-archive.org, it is mentioned that "Save is a mobile app designed to help users preserve, protect and amplify audio / video media"

But currently I am not finding any options to upload the audio files.

So, do we support audio files too on the Save App?

**Comment by tladesignz** [comment]
Theoretically, iOS' "Photos" app stores audio, too. Practically, that doesn't happen.

However, Save App also has a so called "Share Extension" which allows you to share media from other apps into Save.

E.g. use the "Voice Memos" app to record some audio, then share that with Save using the "Share" feature inside that "Voice Memos" app. You may need to activate sharing with Save first, by tapping "More" at the end of the app list.

**Comment by purvi-ranawat** [comment]
Sure. I am able to upload the audio files by following the process mentioned. Hence now closing the issue
