### ISSUE TITLE
[Android] : Whole screen is getting scrolled if we try to scroll project names from top navigation

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/openarchive-ios#142]
Steps to reproduce;:

1)Open the Save app on Android device
2) Create two to three new projects
3) Try to scroll the project name in the top navigation

Expected result:
Only project name should get scroll

Actual result:
The whole screen gets scroll

Note: On iOS device it works fine.
Tested on Samsung Galaxy A70 Android version 9

![Screenshot_20190725-204834_SAVE (1)](https://user-images.githubusercontent.com/8190141/61887001-603cfc80-af1e-11e9-967a-d6415f6465e9.jpg)

**Comment by tladesignz** [comment]
Unfortunately I can't transfer this issue, so please remove and recreate here: https://github.com/OpenArchive/openarchive-android/issues/
