### ISSUE TITLE
[Android: Media is not getting uploaded

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/openarchive-ios#144]
I have created new project on Android device and tried to upload image (82 kb), it shows Ready to Upload and Next button. When I clicked on Next the image enlarged with upload symbol at top right. When clicked on upload symbol it took me back to the Ready to upload screen.

**Comment by tladesignz** [comment]
Unfortunately I can't transfer this issue, so please remove and recreate here: https://github.com/OpenArchive/openarchive-android/issues/
