### ISSUE TITLE
The last entered text on the preview screen gets deleted when we click the Significant Content Flag

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/openarchive-ios#147]
Steps to reproduce:
1)Login to Save app
2) Select any media from camera roll
3) On preview screen enter text in any one option, Add People, Add Location, Add Notes
4) Click on the Flag icon to indicate the Significant content

Expected result: The text entered earlier should not get deleted and the flag is selected

Actual result: The text entered earlier gets deleted and flag is selected

Tested on iPhone XR iOS 12.3. Save app version 36

**Comment by tladesignz** [comment]
Thanks for catching this!

**Comment by foundscapes** [comment]
Tested testflight v. 37 on iphone 6s/ios 12.3.1 and could not reproduce - all metadata was in fields after selecting flag icon
