### ISSUE TITLE
Able to create project with only space as the project name

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/openarchive-ios#148]
When we create the project using only space characters in the project name, it is allowing me to create the project without any error. 

Below is the screenshot :

![space as the project name](https://user-images.githubusercontent.com/8190141/62002945-e37f6d80-b12b-11e9-8279-eff994f5cfcb.jpg)

**Comment by tladesignz** [comment]
Thanks for catching this!
I'll added a check and now trim the project name (remove whitespace at beginning and end) as Nextcloud will do the same.

**Comment by foundscapes** [comment]
Tested v. 37 testflight on iphone 6s/ios 12.3.1 and was not allowed to create a project w/ spaces for names
