### ISSUE TITLE
Able to create project with only special characters as the name 

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/openarchive-ios#149]
I am able to create the project name with the special characters which are not allowed in the file name.

Also, I am able to create the project only with special characters as the name

I have tried this on Iphone XR - IOS version 12.3

Test Flight version : 36

Below is the screenshot :

![special characters in project name](https://user-images.githubusercontent.com/8190141/62003034-c21f8100-b12d-11e9-88f0-db45b1a77359.jpg)

**Comment by tladesignz** [comment]
Turns out, only backslash is a disallowed character for WebDAV / Nextcloud folder names. I disabled that. If users want to make their life hard by using names like this, I won't hinder them. There might be valid use cases where some of these symbols make sense.

**Comment by foundscapes** [comment]
interesting, great find @purvi-ranawat! 

tested test flight 37 on iphone 6s / ios 12.3.1
I still can't create a project name w/ a backslash @tladesignz
