### ISSUE TITLE
Support Custom Media Picker (was Upload from Home)

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#15]
![00_oa-upload-from-home](https://user-images.githubusercontent.com/36669955/49612537-9ff0ad00-f96a-11e8-90e3-c8862debb7ba.png)

**Comment by tladesignz** [comment]
Regarding the image picker you designed here: Please note, that creating that component itself is quite some work. The one you can see in the current app version is, what is provided by iOS itself. Improving that is not an option. I would need to reinvent it from scratch.

There's a couple of projects out there implementing their own image picker:

- https://cocoapods.org/pods/ImagePicker
- https://github.com/ytakzk/Fusuma
- https://cocoapods.org/pods/ALCameraViewController
- https://github.com/tilltue/TLPhotoPicker

There's probably more if you search hard enough. If you do, please keep an eye on the license!

There should be a conscious decision, if one of these is good enough or if you really want to pay for developing your own.

**Comment by cstiens** [comment]
I agree that the custom picker should be a conscious decision. For the initial implementation, it's okay to use the standard picker.

**Comment by n8fr8** [comment]
We'll discuss this more after the holidays. For now, standard is good enough!

**Comment by tladesignz** [comment]
Here is an even longer list for custom pickers:
https://stackoverflow.com/questions/20756899/how-to-select-multiple-images-from-uiimagepickercontroller

**Comment by foundscapes** [comment]
I will review the Objective C options but for Swift, the top candidates are:

- TL PhotoPicker https://github.com/tilltue/TLPhotoPicker updated 4 days ago - supports picking from various albums, selected order index, display video duration.

- DK - https://github.com/zhangao0086/DKImagePickerController  updated 9 days ago - Supports filtering albums and sorting by type. Supports landscape, iPad, and orientation switching. Supports batch exports PHAsset to files.

- Asset Picker View Controller updated 3 months ago https://github.com/DragonCherry/AssetsPickerViewController - no prioritization, but supports many languages

**Comment by foundscapes** [comment]
TLPicker chosen, not able to indicate if media was already uploaded, we will consider this as a future feature. Issue #16
