### ISSUE TITLE
Need popup to explain that to Save to IA, one needs to create an account

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/openarchive-ios#152]
When one chooses the IA, they will need a popup to explain that they need an account there before keys can be generated. Feedback from community: "this wasn't clear. i thought it was saying if i “hit refresh in the corner” that it would somehow get the keys for me"

Popup language: you will need to log in or create an Internet Archive account in order to send and preserve Save media at the Internet Archive.

**Comment by tladesignz** [comment]
Available in new build.
