### ISSUE TITLE
investigate reducing app binary size

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/openarchive-ios#153]
Right now it reports 50MB on the app store listing. Can we make it smaller?

https://developer.apple.com/library/archive/qa/qa1795/_index.html

**Comment by tladesignz** [comment]
I did the following:

- Split up asset catalog, so not all assets end up doubly in the app package (b/c share extension).
- Reduced resolution for images used in onboarding slideshow by 50%, which seems still good enough.
- Don't bundle images used for screenshot generation with app.
- Removed unused font files from build target.
