### ISSUE TITLE
"Skip" button on first screen

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/openarchive-ios#161]
![IMG_4472](https://user-images.githubusercontent.com/2231711/64288761-b6d32880-cf17-11e9-9b00-3a0564c9a1c8.PNG)
@tladesignz do we still need this skip button since it takes you back to server setup when you add media anyway, what is the benefit? Seems to cause confusion.

Thanks!

**Comment by tladesignz** [comment]
From https://developer.apple.com/app-store/review/guidelines/ :

> Account Sign-In: If your app doesn’t include significant account-based features, let people use it without a log-in. Apps may not require users to enter personal information to function, except when directly relevant to the core functionality of the app or required by law. If your core app functionality is not related to a specific social network (e.g. Facebook, WeChat, Weibo, Twitter, etc.), you must provide access without a login or via another mechanism. Pulling basic profile information, sharing to the social network, or inviting friends to use the app are not considered core app functionality. The app must also include a mechanism to revoke social network credentials and disable data access between the app and social network from within the app. An app may not store credentials or tokens to social networks off of the device and may only use such credentials or tokens to directly connect to the social network from the app itself while the app is in use.

My recommendation: If you want to avoid issues with Apple, leave it in.

**Comment by foundscapes** [comment]
Annoying. In order to use the app, people must connect, so it's confusing for folks.

**Comment by foundscapes** [comment]
revisit when we can
