### ISSUE TITLE
iOSify the app - Update Main Scene UI + iCloud Picker

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/openarchive-ios#164]

**Comment by tladesignz** [comment]
Will be contained in build 41.

**Comment by foundscapes** [comment]
@tladesignz 
new UI changes:

1) remove doc picker 
2) Put plus in middle 
3) move trash the right 
4) remove select on the left 
5) keep multi edit on left (which is grayed out when nothing is tapped/held for batch)
