### ISSUE TITLE
Problems when Sharing from Voice Memos

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/openarchive-ios#166]
on both iphone XR and iphone 6s on ios 12.4.1, reproduced twice:

Sharing from voice memos only works when adding to a project that's already open in the active workspace. It does not work when creating a new project or when choosing to add to a project that is not in the workspace.

to reproduce:
+ Share a voice memo from the Voice Memos app into Save.
+ When prompted, choose to create a new project. Name it whatever.
+ You'll be sent back to the Voice Memos app, and will get a notification that your file is ready for upload. Don't tap the notification.
+ Return to Save. The new project will not be there.

The same thing happens when you try to add to an existing project that is not currently open.

**Comment by tladesignz** [comment]
I think I nailed it. Please test on next build (47). Will TestFlight after transfer is done.
