### ISSUE TITLE
Home View (with media)

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#17]
- [ ] View for 'All' with multiple uploads
![oa-multiple-all](https://user-images.githubusercontent.com/36669955/49614444-e72d6c80-f96f-11e8-9912-c1e065da4076.png)
Info will be editable here. Serves as an 'activity view' to see everything you've uploaded, when, and where to.

- [ ] View for a project with multiple uploads
![oa-multiple-project](https://user-images.githubusercontent.com/36669955/49614477-03c9a480-f970-11e8-95f5-df76a0aa7b39.png)
Within the project, uploads just fall in line so you see the entire album but not broken up into uploads. You can still edit info by tapping on individual media like in #13

**Comment by n8fr8** [comment]
For now, same size grid of thumbnails in a collection is acceptable

**Comment by tladesignz** [comment]
Superseded by #36.
