### ISSUE TITLE
Flow through Share Extension

### ISSUE THREAD

**Issue by tladesignz** [OpenArchive/openarchive-ios#26]
There's another add/upload flow through the Share Extension. Please refer to the current app version on how this currently works.

We can only pick images and videos. All other media (like voice recordings, PDFs in iBooks, various data from other sources like iCloud, Dropbox, Google Drive etc.) need to be added via that facility.

Data we get there is (sometimes edited) copies, not references, so not possible to match with stuff from the camera roll (aka. "Photos" built-in app), even if that one was the actual source.

The Share Extension is somewhat limited. So we cannot just start the full app. We can show one scene and maybe another, but that's it, so e.g. the spaces need to be set up in advance.

We can allow the user to share one, an arbitrary number of or an unlimited number of items at once with OA. Although I would suggest that the user can only select one project to share it with, otherwise that could get funky.

Once our Share Extension closes, control is lost. The only thing which should keep running in the background are uploads, which were started by the user. Only as long as there's no (network) error, of course.

**Comment by tladesignz** [comment]
Have a look at messaging app like iMessage, Signal, WhatsApp and the like to get an idea what is possible in Share Extensions! Note the differences to the app's normal flow!

**Comment by n8fr8** [comment]
The other issue this brings up is how to display non image/video entries inside the app.

**Comment by tladesignz** [comment]
Follow-up in #34.
