### ISSUE TITLE
no auto-restart when losing connection & uploading to nextcloud 

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/openarchive-ios#27]
If you are uploading a file and you lose internet connection before the transaction is completed the upload pauses and it does not restart when you get access to the internet again.

**Comment by foundscapes** [comment]
(this is feedback from Fabby's ux testing)
You also can not restart the upload manually, and you need to cancel that upload or the system will not allow you to start a new one.

**Comment by tladesignz** [comment]
We can't do anything about automatically restarting as long as the app is not running. As soon, as the background upload stops due to an error, it's done.

Another story, when the app is running. Need to investigate. Actually, it probably needs the queue feature, which does not exist, yet.

**Comment by foundscapes** [comment]
Ok, so we need to address this twofold:

1) if the upload stops when it is background uploading (app is closed), then we need to make sure to let the user know that it failed and why/have them send crash feedback to us

2) if it doesn't resolve with the queue, we definitely need a way to let people know that they need to re-upload.

Since the goal is to have continuous uploading with a status bar, whether or not the the app is open, we need to make sure the user is aware either way.

**Comment by tladesignz** [comment]
Will be fixed with #14
