### ISSUE TITLE
Determine limitations of background uploading

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/openarchive-ios#29]
- what is the largest file we can upload in the background?
- what limitations do we face in trying to upload multiple files in the background?
- can we use background process / thread to stay alive, check for further files to upload?

**Comment by n8fr8** [comment]
Look into HTTP upload resuming

**Comment by n8fr8** [comment]
Resuming chunked uploads works with Nextcloud, and has been implemented in their Android client: https://github.com/nextcloud/server/issues/673

With iOS, we should upload all we can while we are allowed to run in the background, and persist where we left off. When the app is re-opened, we can continue any unfinished uploads.

**Comment by tladesignz** [comment]
Followed up by #53 and #56.
