### ISSUE TITLE
project <-> space mapping: 1 to 1 or 1 to many

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/openarchive-ios#31]
let's discuss here!

**Comment by n8fr8** [comment]
I propose this, but please feedback!

- A project can only have one space. When you create the project, and if you have more than one configured space, you can choose the space. Otherwise, the project defaults to the one configured space.

- The user can change the space in the project configuration at any time.

- We don't back sync or resync anything that has already been uploaded when the space is changed. We only look forward and upload new things to the new space.

**Comment by n8fr8** [comment]
#24 touched upon this before

**Comment by n8fr8** [comment]
and #25

**Comment by tladesignz** [comment]
I started an Entity-Relationship-Model diagram to have an informed discussion.

This is the current version:

![ERM](https://raw.githubusercontent.com/OpenArchive/openarchive-ios/master/docs/ERM.png)

It's done in [Dia](https://en.wikipedia.org/wiki/Dia_(software)). You can download it here for [Windows](http://dia-installer.de) and [MacOS](http://dia-installer.de/download/macosx.html). Linux users best use their software package manager.

I put a copy on Google Docs for collaborative editing. Send me a private message with your Google ID, if you want access.

**Comment by tladesignz** [comment]
Please note, that I'm basically stuck in development, as long as this is not decided. The basic "information model" (which boils down to this ERM here) is vital for project progress, as it influences everything, esp. the UI and UX.

With our first version, I could implicitly deduct this, but now the project became too big, and the UI designs are not complete and stringent enough to be able to deduct it from there.

I suggest the following course of action:

1. (evtl. change and then) decide on the information model. (@foundscapes, @n8fr8, @cstiens, @tladesignz)
2a. Implement model structure in code. (@tladesignz) 
2b (at the same time) Update UI designs accordingly. (@cstiens)
3. Implement UI. (@tladesignz)

**Comment by n8fr8** [comment]
Thank you for documenting this. An ERM works great, and maps well to the ORM (Sugar Record) I am already using for Android. I have Space, Project and Asset ("Media") implemented, but not Collection yet.

Overall, this looks very close. I need to review my proposal for the flat file archive persistence, to ensure this has all the data to create that structure.

Asset
1. We may need to store mime-type, file length, hash and other file metadata info.
2. This might be the place we store upload/sync status, and what chunk/progress we are at
3. Would "tags" handle the graphic warning flag? Can we overload "tags" to handle a variety of special cases?

Collection
1. I think a collection may also have a title, location or other description type info. Maybe I am confusing it with Project?

Project->Space
1. Happy for this to be one-to-one relationship, but we should still have the ability, at some point, to move a Project to another Space. Again, this wouldn't require back-syncing, just future sync to the new Space.

**Comment by n8fr8** [comment]
Asset should include "remote path" to where it has been synced remotely, for future delete or move options

**Comment by tladesignz** [comment]
I'll close this one, as we basically settled on the model now.

Regarding your comments about the properties: 

> Asset
>
> 1. We may need to store mime-type, file length, hash and other file metadata info.

"uti" is the apple-y way of a MIME type. It's convertable and I output the MIME type.
File length is derived on the fly from the file.
Hash also (as of now, but that might change).

> 2. This might be the place we store upload/sync status, and what chunk/progress we are at

True, which now is in the meantime (with a boolean flag) and will evolve.

> 3. Would "tags" handle the graphic warning flag? Can we overload "tags" to handle a variety of special cases?

This is just a leftover from the old version. I'll adapt stuff like that appropriately, as I move along the project.


> Collection
> 
> 1. I think a collection may also have a title, location or other description type info. Maybe I am confusing it with Project?

Probably. In the UI sketches I remember, there's no UI to edit collection metadata. A collection is simply a number of assets which are uploaded together.

Location must come from the asset, as that's where the GPS is stored, if any.

> Project->Space
> 
> 1. Happy for this to be one-to-one relationship, but we should still have the ability, at some point, to move a Project to another Space. Again, this wouldn't require back-syncing, just future sync to the new Space.

Sure. I designed my projects, so, that they can be unattached of any space. (At least temporarily).
