### ISSUE TITLE
Add Media from Share Sheet

### ISSUE THREAD

**Issue by kckthx** [OpenArchive/openarchive-ios#34]
Uploading from share sheet workflow
(I accidentally uploaded this to the android github first but closed it)

![oa-add-from-share-sheet-workflow](https://user-images.githubusercontent.com/36669955/52820735-73e05f00-3072-11e9-88a8-4de2262282ea.jpg)

**Comment by tladesignz** [comment]
Still missing: 
- Create new project. (Should be doable)
- Notification (Not so sure, if that will work without a push server...)

**Comment by tladesignz** [comment]
Unbelievable: One can trigger user notifications from share extensions! Done!
