### ISSUE TITLE
Settings/Account View

### ISSUE THREAD

**Issue by kckthx** [OpenArchive/openarchive-ios#35]
edit project, server login and credential setting screens aren't fine tuned yet, but this is the projected layout of the high level settings/account screen.

![oa-settings](https://user-images.githubusercontent.com/36669955/52820819-b1dd8300-3072-11e9-8a28-4186754353eb.jpg)

**Comment by foundscapes** [comment]
@tladesignz please rename "Author Metadata" to profile

**Comment by tladesignz** [comment]
@foundscapes Done in the last commit.

**Comment by tladesignz** [comment]
@kckthx Since user avatars now became server favicons, I would need another placeholder icon. To show, as long as the favicon is not loaded or a server absolutely doesn't have one. Can you provide one, please? Format: SVG, as usual. Thanks a lot!

**Comment by tladesignz** [comment]
Project settings superseded by #40!

**Comment by n8fr8** [comment]
One scene, Two modes: New, Edit mode

New
- Textfield name: editable for user (unless they browse projects)
- License Toggles Invisible, default off values
- Actions: Browse Project -> Select Folder -> set name, make field read-only

Edit
- Textfield name: editable
- License Toggles Visible, default off
- Actions: Archive, Delete

**Comment by tladesignz** [comment]
What should "archive" actually do?

**Comment by tladesignz** [comment]
Ah, of course. Hide it in the main scene.
