### ISSUE TITLE
Home with no "ALL" tab

### ISSUE THREAD

**Issue by kckthx** [OpenArchive/openarchive-ios#36]
**Home screen with items waiting to be uploaded**
- badge on project name indicates items waiting for upload
- Blurred images indicate they have not been uploaded
- icon takes user to the preview/upload view
- New project tab has moved to the left side for easy adding with several projects activated

![oa-home-done](https://user-images.githubusercontent.com/36669955/52820997-2c0e0780-3073-11e9-83e9-2a35db282a53.png)

**Home screen while uploading items to server**
- Manage option is available and takes user to the upload manager screen
- upload progress indicated (3-9 and "UPLOADING" instead of "WAITING")
- badge is gone from project tab once images are uploaded

![oa-upload](https://user-images.githubusercontent.com/36669955/52821034-4811a900-3073-11e9-9b13-56e53072328d.png)

**Home screen with everything uploaded**
![oa-home](https://user-images.githubusercontent.com/36669955/52821235-d4bc6700-3073-11e9-95d1-cf780ccbaa08.png)

**Comment by tladesignz** [comment]
Sorry, the badge is not possible with the currently used [MDCTabBar](https://material.io/develop/ios/components/tabs/).

It's highly opinionated and won't ever look like in the design template.

Please create another issue, if you want to have your own tab bar implemented or if you like something like a leading asterisk (*) or something.

**Comment by tladesignz** [comment]
(All the rest is implemented)
