### ISSUE TITLE
Empty Project

### ISSUE THREAD

**Issue by kckthx** [OpenArchive/openarchive-ios#37]
A project with no media imported or uploaded
![oa-project-empty](https://user-images.githubusercontent.com/36669955/52821320-164d1200-3074-11e9-9269-fece34731e38.png)

**Comment by tladesignz** [comment]
@kckthx Sorry, this is annoying, but I would need that "+" as an image (white on transparent).

If I do a textual "+", it doesn't get properly vertically centered, and before I unpack my rather weak GIMP skills, I'd prefer you would do it. Thanks a lot!

**Comment by kckthx** [comment]
[Add-Button.zip](https://github.com/OpenArchive/openarchive-ios/files/2906114/Add-Button.zip)
No worries -- here is the "+" and the whole button!

**Comment by tladesignz** [comment]
Thanks a lot!
