### ISSUE TITLE
Add 'Browse' button to New Project view

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#38]
Do not implement this yet, until we stew on it!

![oa-new-project](https://user-images.githubusercontent.com/1434597/53520875-55c82500-3a9c-11e9-8cec-c4af5bf7707a.png)

**Comment by foundscapes** [comment]
change "curate" to "create"?

**Comment by n8fr8** [comment]
Will review latest testflight with @cstiens and make a decision
