### ISSUE TITLE
Licensing options, per-server type endpoint (was Project settings)

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#40]
<img width="906" alt="project-settings_v2" src="https://user-images.githubusercontent.com/1434597/53521884-ddaf2e80-3a9e-11e9-9132-9ea36b241e81.png">

For a server, creative commons would be off by default.
For internet archive, it is on and cannot be turned off. (We probably need to handle that better)

**Comment by n8fr8** [comment]
We will have licensing options consistent for all sites. NO special handling for Archive.org, since users should be able to choose there still.

**Comment by cstiens** [comment]
> We will have licensing options consistent for all sites. NO special handling for Archive.org, since users should be able to choose there still.

That is fine. From our previous conversations about this, I thought the licensing options didn't translate when you upload to archive.org. @n8fr8 do they?

**Comment by tladesignz** [comment]
@cstiens That was a misunderstanding. Archive.org *does* have a field for licensing options and they are happy with different licenses or none expressed at all, not just CC.

I'll close this now, since I implemented the UI already. Feel free to re-open, if something during testing comes up.
