### ISSUE TITLE
Ability to add detailed info to a single piece of media

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#41]
We need the ability to add notes or additional fields of information to a piece of media. With this design, the pencil icon would only show in this view.

![oa_add-info-fullphoto_v2](https://user-images.githubusercontent.com/1434597/53523490-8f9c2a00-3aa2-11e9-8ed8-7fa66d46dffd.png)

**Comment by tladesignz** [comment]
Was implemented with #52.
