### ISSUE TITLE
auto-discovery of API endpoint for common servers

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/openarchive-ios#42]
The user shouldn't have to know more than the domain of their server

**Comment by n8fr8** [comment]
examples:

Owncloud: remote.php/dav

NextCloud: https://cloud.guardianproject.info/index.php/login

**Comment by tladesignz** [comment]
Related with #45.

There is a "well-known" mechanism. There should to be some file/folder structure inside /.well-known/ at least on Owncloud/Nextcloud servers. However, I only saw this in conjunction with CardDAV/CalDAV. Not sure about regular WebDAV file access.

It seems very underdocumented. See e.g. https://docs.nextcloud.com/server/14/admin_manual/issues/general_troubleshooting.html

**Comment by n8fr8** [comment]
implement so far: if the user doesn't enter a scheme, auto prepends "https://".
if the user doesn't enter a path, we auto append a default path for Nextcloud.

**Comment by n8fr8** [comment]
@foundscapes this is an area where end-user documentation is key
