### ISSUE TITLE
Better dummy icon for servers

### ISSUE THREAD

**Issue by tladesignz** [OpenArchive/openarchive-ios#46]
We switched the meaning of the icon from user avatar to server favicon. 

In the rare cases, we can't fetch a favicon and in the situation before we fetched it, we need a placeholder icon.

Currently, I'm using the old one, but it shows a perso. That doesn't make much sense.

Is it possible to provide one which is related to web servers?

Transparent SVG, as always. Thanks!

**Comment by kckthx** [comment]
[server.svg.zip](https://github.com/OpenArchive/openarchive-ios/files/2946437/server.svg.zip)
got it @tladesignz

**Comment by tladesignz** [comment]
Thanks! b1672650f6101c5b38157f5a0caac5450daa8ab0
