### ISSUE TITLE
Import to new project – goes back to first project

### ISSUE THREAD

**Issue by kckthx** [OpenArchive/openarchive-ios#47]
From the home screen I 

**1. created a new project**
when I tap "done" it takes me back to the last project I had selected, not the one I just created.

**2. tap fab button to import new media**
Still can't batch select -- is that coming?
should go straight to preview view after selecting media -- not sure if this has to do with the fact that there is no batch select and therefore not a "DONE" button to tap?

**3. after image is selected, the photo gallery view closes and I am taken back to the first project--not the one I just created **
If I scroll over and open the project I just imported to, the image is there and every other import will open in that project

I created 6 projects and this happens every time.
@tladesignz

**Comment by tladesignz** [comment]
With iOS' integrated UIImagePicker, multi-select is not possible.
See https://stackoverflow.com/questions/20756899/how-to-select-multiple-images-from-uiimagepickercontroller

This ties back to #15.

**Comment by foundscapes** [comment]
Still happening on iphone 6s/xr

**Comment by kckthx** [comment]
also happening on iphone 8
