### ISSUE TITLE
Delete file from preview before import/upload

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/openarchive-ios#51]
Use case: if someone adds a file accidentally before uploading, make it easy to delete from preview screen when "waiting" to upload.

**Comment by cstiens** [comment]
@tladesignz Did you need any UI direction for this one? I know it wasn't in the original design.

**Comment by tladesignz** [comment]
I implemented it with the standard "swipe left and hit the red 'delete' button" behaviour, which is typical on iOS UITableViewControllers.

I suggest you have a look at it in the next TestFlight version. If you don't like it, you can always come up with something better.

**Comment by tladesignz** [comment]
Looks like you like it. :-)
