### ISSUE TITLE
Compression Options

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/openarchive-ios#54]

**Comment by n8fr8** [comment]
When and how can the user set the resolution of media they want to import and upload

**Comment by tladesignz** [comment]
Note: The right time to do that, is when importing something into the app: After returning from the image picker inside the app (or inside our self-created image picker) and in the share sheet.

**Comment by n8fr8** [comment]
Just noticed video compression happening in the latest testflight build... great work! I assume this came from some of the same knowledge we gained in Keanu.

**Comment by foundscapes** [comment]
yay compression! thank you @tladesignz!

**Comment by tladesignz** [comment]
Well, aah, how do I tell you that...
It was there almost from the beginning. I don't get the full video file. Videos are always exported. And exports need to have a target defined, quality-wise and format-wise.

**Comment by n8fr8** [comment]
Great! Let's talk about what options we can expose to the user in future work.

**Comment by tladesignz** [comment]
The Options:

- [PHVideoRequestOptions](https://developer.apple.com/documentation/photokit/phvideorequestoptions)
- [PHVideoRequestOptionsVersion](https://developer.apple.com/documentation/photokit/phvideorequestoptionsversion)
- [PHVideoRequestOptionsDeliveryMode](https://developer.apple.com/documentation/photokit/phvideorequestoptionsdeliverymode)

**Comment by n8fr8** [comment]
This is an interesting feature:
"case current
Request the most recent version of the video asset, reflecting all edits.
case original
Request a version of the video asset without adjustments."

**Comment by n8fr8** [comment]
This seems like a natural "Data Settings" slider option:

case automatic

Photos automatically determines which quality of video data to provide based on the request and current conditions.
case highQualityFormat

Photos provides only the highest quality video available.
case mediumQualityFormat

Photos provides a video of moderate quality unless a higher quality version is locally cached.
case fastFormat

Photos provides whatever quality of video can be most quickly loaded.

**Comment by foundscapes** [comment]
need ui @cstiens @kckthx

**Comment by foundscapes** [comment]
General setting vs. individual item setting

**Comment by n8fr8** [comment]
@tladesignz can you provide detail here on what you have currently implemented in terms of photo and video compression?

**Comment by tladesignz** [comment]
When importing from the Photos app from inside Save:

[Photos are exported](https://github.com/OpenArchive/openarchive-ios/blob/master/Shared/Models/AssetFactory.swift#L112) using [these options](https://github.com/OpenArchive/openarchive-ios/blob/master/Shared/Models/AssetFactory.swift#L35-L43):

```Swift
    private static var hiResOptions: PHImageRequestOptions = {
        let options = PHImageRequestOptions()
        options.version = .current // The resulting image is the rendered output from all previously made adjustments.
        options.deliveryMode = .highQualityFormat // Photos provides only the highest-quality image available, regardless of how much time it takes to load.
        options.resizeMode = .none // Photos does not resize the image asset.
        options.isNetworkAccessAllowed = true // A Boolean value that specifies whether Photos can download the requested image from iCloud.

        return options
    }()
```

[Videos (and theoretically audio, if the camera roll had audio-only) are exported](https://github.com/OpenArchive/openarchive-ios/blob/master/Shared/Models/AssetFactory.swift#L136) using [these options](https://github.com/OpenArchive/openarchive-ios/blob/master/Shared/Models/AssetFactory.swift#L45-L52):

```Swift
    private static var avOptions: PHVideoRequestOptions = {
        let options = PHVideoRequestOptions()
        options.version = .current // The resulting video is the rendered output from all previously made adjustments.
        options.deliveryMode = .highQualityFormat // hotos provides only the highest quality video available.
        options.isNetworkAccessAllowed = true // A Boolean value that specifies whether Photos can download the requested video from iCloud.

        return options
    }()
```

When importing through the Share Extension, there is no possibility to steer the quality. [We just take what we get.](https://github.com/OpenArchive/openarchive-ios/blob/master/ShareExtension/MainViewController.swift#L228-L246)

Of course there would be the possibility later to re-render everything, but that will burn a lot of battery. And I'm not sure if it's a good idea to become a video rendering tool. There are apps doing that already, of course.

**Comment by n8fr8** [comment]
@foundscapes based on calls with users, I think we should expose the compression options in the app. Let's revisit this!

**Comment by n8fr8** [comment]
I think we at least need a global setting to use "fastFormat" for import for low bandwidth users

**Comment by foundscapes** [comment]
100% Agree!!

**Comment by tladesignz** [comment]
> I think we at least need a global setting to use "fastFormat" for import for low bandwidth users

So set

```Swift
options.deliveryMode == .fastFormat
```

and

```Swift
options.isNetworkAccessAllowed = false
```

or just the first and still (potentially) allow download from iCloud, if the user moved their files there?

**Comment by tladesignz** [comment]
Will be available in the next build.
