### ISSUE TITLE
Upload auto-retry

### ISSUE THREAD

**Issue by tladesignz** [OpenArchive/openarchive-ios#57]
Pursues questions which was posed by issue #14:

- Stop conditions? How to distinguish? Error numbers? Parsing error texts?
- Number of times?
- Frequency?
- Frequency decline?

**Comment by foundscapes** [comment]
@n8fr8 can you help with this?

Perhaps cap tries at 10 errors
distinguish error conditions server vs. internet/network

**Comment by tladesignz** [comment]
This looks like a viable idea, how to handle this class of problems.

https://dzone.com/articles/understanding-retry-pattern-with-exponential-back

**Comment by tladesignz** [comment]
Should work as follows:

- Check every minute.
- If no network connection - come back later.
- If network connection, try upload.
- If failed, increase retry counter of upload, wait with that upload for retry ^ 1.5 minutes (see [plot](http://fooplot.com/?lang=en#W3sidHlwZSI6MCwiZXEiOiJ4XjEuNSIsImNvbG9yIjoiIzAwMDAwMCJ9LHsidHlwZSI6MTAwMCwid2luZG93IjpbIjAiLCIxMSIsIjAiLCI0MCJdfV0-))
- If retried 10 times, give up with that upload: set it paused. User can restart through unpausing.
- Circuit breaker per space (to reduce load on server):
  - Per Space count failed upload attempts.
  - If failed 10 times, wait 10 minutes before any other upload to that space is tried.
  - If one upload retry failed again, wait 10 minutes again before next upload is tried.
  - If one upload succeeded, reset space's fail count.

User can pause and unpause a scheduled upload any time to reset counters and have a retry immediately.
