### ISSUE TITLE
Upload Manager needs to show errors

### ISSUE THREAD

**Issue by tladesignz** [OpenArchive/openarchive-ios#58]
Pursues questions which was posed by issue #14:

@cstiens said, there's already a solution. Please add here. Thanks!

**Comment by n8fr8** [comment]
We need a quick solution for this @cstiens @kckthx

**Comment by cstiens** [comment]
@n8fr8 @tladesignz Here you go! When there's an error, the error icon replaces the progress indicator as shown in the first mockup. I've included an svg of that icon. Tapping on it, brings up and alert with the error message. I imagine there are a couple basic cases— 

1) An error where there's a chance of having success if you retry. (This is represented in the second view)
2) An error where there's nothing to do but remove the item from the queue. This is represented in the third view)

If we can't reach this level of sophistication with errors, I recommend always using the modal with two buttons. That way, in the case where a retry will fix it, the user has the option readily available. 

<img width="758" alt="Screen Shot 2019-04-10 at 3 22 42 PM" src="https://user-images.githubusercontent.com/1434597/55910655-912e3700-5ba4-11e9-95cb-2abadf4cab33.png">

**Comment by tladesignz** [comment]
That looks great!
See, @n8fr8, that's why I wait on designs. I wouldn't have come up with something like this.

@cstiens, I recognized something about the icons:

The one you provided here has a size of 17 x 17 px defined (canvas, as well as circle diameter). Even if it's a vector graphic, the defined target size will be honored!

There are certain elements, esp. `UIButton` where I can't control the sizing of icons used within, so no auto-stretch!

Additionally, in the IDE they end up even smaller. I'm not sure if that's because of the SVG to PDF conversion or because Xcode likes to do that.

I edited this one provided with Inkscape to make it bigger and ended up with using 31 px size in Inkscape which lead to 24 px size in Xcode. That looks like you intended it to be on your designs.

Please cross-check all icons you feel are too small and provide improved ones.
I checked all icons now, and most of them are way smaller than 24 pixel.

**Comment by tladesignz** [comment]
The easiest way to test this is to change your password on the server *after* you connected the space and *before* uploading something.
