### ISSUE TITLE
Imported items don't group into single "Waiting" group

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/openarchive-ios#62]
I can only select one media item at a time in the Camera Roll, and so must click (+) each time to add one by one. As I add each item, they are not grouped into a single "Waiting to upload" group.

![IMG_1536](https://user-images.githubusercontent.com/30851/55106970-894f9c80-50a6-11e9-9c81-0f8aa6431fa2.PNG)

**Comment by n8fr8** [comment]
Also the up arrow icon is SUPER tiny on my iPod Touch screen. I think there is another ticket discussing that...

**Comment by foundscapes** [comment]
yes, see #63

**Comment by tladesignz** [comment]
Regarding icon size, see my comment on #61: I guess, the icons need to get bigger inside their images.

Besides that, they are as big as adviced and also as big as Apple says they should.
