### ISSUE TITLE
New App Icon

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#67]
[save-logo.pdf](https://github.com/OpenArchive/openarchive-ios/files/3015945/save-logo.pdf)

**Comment by tladesignz** [comment]
Sorry. For app icons, PDFs cannot be used, unfortunately.

Please provide a 1024 x 1024 pixel PNG file as source.

Also: Don't do the corner rounding. The IDE will do that itself. If you didn't get it exactly like the IDE, the icon will show white borders. Also, Apple changed the exact rounding once, so better leave that to Apple.

**Comment by tladesignz** [comment]
And NO WHITE BORDERS!

**Comment by cstiens** [comment]
@tladesignz Thank you for providing the specs! I'm so glad Apple does their own rounding. They were driving me crazy about it before. ;) I've attached the file you need! 

![save-logo_FINALDECISION](https://user-images.githubusercontent.com/1434597/55194187-f03c8680-5176-11e9-896b-e3c085b1a18f.png)
