### ISSUE TITLE
Enable group/bulk editing

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/openarchive-ios#68]
Make it easy to attribute metadata to bulk uploads

**Comment by tladesignz** [comment]
Please provide spec/UI/UX wireframes.

**Comment by foundscapes** [comment]
that is @cstiens department

**Comment by n8fr8** [comment]
I think #62 will solve this.

**Comment by foundscapes** [comment]
@tladesignz said there is no prefab photo-picker that can allow for multiple files to be chosen at once, which would enable bulk editing

**Comment by tladesignz** [comment]
@foundscapes The opposite, actually. There are pickers, which allow multi-select. @cstiens and you just need to pick one, which suits your UX and UI tastes. Then I will integrate it. As agreed on yesterday.

However, there's not going to be more "bulk editing" than already exists, with another picker. Just one tap less to reach it, maybe, if you want that.

At least, not as long as you come up with another UI which is more "bulky" than currently.

**Comment by foundscapes** [comment]
Now that we've chosen a media picker, can we implement bulk editing from this screen?
![IMG_0319](https://user-images.githubusercontent.com/2231711/57109562-a8b39800-6cea-11e9-91bf-e461e1f31ad7.PNG)
Discussed today w/ @cstiens @kckthx so they can make the UI

**Comment by tladesignz** [comment]
Continued in #98.
