### ISSUE TITLE
Test flag icon

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#69]
@tladesignz Will you test this flag icon to see if it increases the tappable area?

[flag-no-border.svg.zip](https://github.com/OpenArchive/openarchive-ios/files/3040430/flag-no-border.svg.zip)

**Comment by tladesignz** [comment]
I added it. Doesn't seem to make a real difference in size, compared to the other icons.

I'll leave it in the build, so you can test it with the next TestFlight!

![Simulator Screen Shot - iOS 11 4 @ iPhone 5s - 2019-04-04 at 17 38 32](https://user-images.githubusercontent.com/117089/55568713-7e2cea00-5700-11e9-9ecd-6bf34e8c7b23.png)
![Simulator Screen Shot - iOS 11 4 @ iPhone 5s - 2019-04-04 at 17 38 35](https://user-images.githubusercontent.com/117089/55568714-7e2cea00-5700-11e9-90cf-e0a9cd6da63d.png)

**Comment by cstiens** [comment]
Great! Thank you!
