### ISSUE TITLE
How to delete a space?

### ISSUE THREAD

**Issue by tladesignz** [OpenArchive/openarchive-ios#70]
Since the redesign, there's no possibility to delete a space anymore.

Don't we need that?

**Comment by kckthx** [comment]
@cstiens @tladesignz @n8fr8 

![OA-UX-Implementation_v1](https://user-images.githubusercontent.com/36669955/56769472-ea869080-6776-11e9-8e3a-b70fe5611a1c.jpg)

**Note that the action in the top right becomes 'Done' after you are connected to a server.** It should still say connect when you connect for the first time, and then when you navigate back (like in the flow above) the action will be 'Done' 
![OA-fields_left justified-empty](https://user-images.githubusercontent.com/36669955/56769543-1b66c580-6777-11e9-9007-eaed09bb92e2.png)
![OA-fields_left justified-filled](https://user-images.githubusercontent.com/36669955/56769547-1c97f280-6777-11e9-9078-77ea16550f13.png)

**Comment by tladesignz** [comment]
Great, thanks! Flow totally makes sense.
I just wanted to mention here, that when we remove a space, all the assets are going to be removed, too. Isn't "disconnect" a little weak word for that circumstance?
