### ISSUE TITLE
Flagged items not routing into subfolder

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/openarchive-ios#71]
Uploaded 3 files, one was flagged, all wound up in same folder on server, see photos.
<img width="1149" alt="Screen Shot 2019-04-04 at 12 52 58 PM" src="https://user-images.githubusercontent.com/2231711/55584268-b3254680-56d8-11e9-981a-ae5bb02115fe.png">
![IMG_9117](https://user-images.githubusercontent.com/2231711/55584362-e10a8b00-56d8-11e9-9bfe-f14fca3d7cc9.PNG)

**Comment by tladesignz** [comment]
See issue #7: It is still undecided, how the final folder structure on the server should actually be.

Also, there's still no decision, what the "flag" actually should be. Currently, it's still "NSFW".

**Comment by foundscapes** [comment]
Ah ok, so it's not a bug, great. Let's call it "flagged"

**Comment by n8fr8** [comment]
I'll be working on this, so we are ready to go when @tladesignz is back after vacation

**Comment by foundscapes** [comment]
@n8fr8 ok

**Comment by foundscapes** [comment]
@n8fr8 how's this going?

**Comment by foundscapes** [comment]
@n8fr8 @tladesignz this is the last big feature we need to implement, let me know if there's something I can do to help

**Comment by foundscapes** [comment]
@tladesignz for initial popup for Flagged items, it needs to read: "When you flag an item, it is routed into a subfolder within the chosen project folder on the server."

**Comment by tladesignz** [comment]
@foundscapes: Sorry, this is an indirect and incomplete requirement, which I can't follow.

Please create a complete description of how files on a WebDavServer should be layed out. Use a new issue with a proper subject.

Ideas about how this should be done are already outlined in issue #7.

If it turns out, we can't reach a viable layout using GitHub's asynchronous discussion tools, I suggest, @n8fr8, me and you use the next meeting to finalize this once and for all.

**Comment by n8fr8** [comment]
I think we can resolve the upload path issue here. @foundscapes Let's keep other UI discussions about popup and display text on another ticket.

If a media item is flagged in the client UI, then media file (jpg, mp4, etc) and the associated metadata (json) should be uploaded into a subfolder within the current upload batch folder called "flagged".

**Comment by tladesignz** [comment]
I did as wished, as we finally have a spec which defines the file/folder layout. However please note:

- The text is technically wrong. As per spec, it will get routed into a "submission" folder (in OA iOS internally called a "collection"), which name is the timestamp of when it was created.

- The text is wrong when it comes to Internet Archive. There's no possibility to do any subfoldering.

**Comment by foundscapes** [comment]
It seems to be working on our private server, however can you rename the folder so it's not in all caps so it reads: Flagged instead?

**Comment by tladesignz** [comment]
Will be contained in next build.

**Comment by foundscapes** [comment]
Updated language for Flag Popup:

"When you flag an item, it is routed into a subfolder within the chosen project folder on the private server."
