### ISSUE TITLE
Home Actions: Access upload manager, Preview/add info/upload

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#72]
We can discuss on our next scrum, but I wanted to document this.

![OA-upload-manager](https://user-images.githubusercontent.com/1434597/55823902-61a9fc80-5ac8-11e9-8f3c-ad9d3af4b191.png)

The circle progress indicator in the top right indicates the overall progress of everything that is being uploaded at a given time. We will need to consider the design for the state where there is nothing in progress. When a user taps on this icon/indicator, they are taken to the upload manager view where they can see the progress of each item.

The 'level' icon on the 'Waiting to upload' line takes the user to the preview view where they can add information, then upload.

**Comment by n8fr8** [comment]
@kckthx we need the levels icon

**Comment by foundscapes** [comment]
@cstiens may have levels icon

**Comment by cstiens** [comment]
@n8fr8 @tladesignz @foundscapes Here it is!
[ic_levels.svg.zip](https://github.com/OpenArchive/openarchive-ios/files/3065627/ic_levels.svg.zip)

**Comment by tladesignz** [comment]
I replaced the "Upload" button with the level icon and removed the "Manage" button on the collection headers.
Instead I added a button to reach the upload manager in the top right. It's currently not active and just shows the state, when something needs to be manually triggered to upload. I leave it this way for now, as it seems, the discussion about how this should work isn't finished.

Happy, if you decide on this during my vacation. (Please consider error state! See #58)

**Comment by cstiens** [comment]
From scrum discussion: 
- [ ] Switch levels icon back to a word/phrase. We will think more about this, but are leaning toward 'Next' or 'Add Info'
- [ ] Progress indicator in the top right corner should be an active status indicator.

**Comment by kckthx** [comment]
When there is no media being uploaded, there will be no icon in the top right
![OA-no-upload manager](https://user-images.githubusercontent.com/36669955/56318951-fdb9b080-6125-11e9-886f-dd3f9a6e9e6d.png)

When there **IS** media being uploaded, the icon will show in the top right with the number remaining
![OA-upload manager](https://user-images.githubusercontent.com/36669955/56318952-fdb9b080-6125-11e9-8daa-79beb8818320.png)

**Comment by kckthx** [comment]
@cstiens @foundscapes

**Comment by kckthx** [comment]
We talked in the scrum about how the word 'Waiting' feels like I'm waiting on the app to do something, or for a network connection. Not like it is waiting for me to do an action. Some word ideas, instead of 'WAITING'

- Ready
- Queued
- Ready to upload

Thoughts? Suggestions?

**Comment by cstiens** [comment]
I think it should read "Ready to upload" with 'Next' as the action button on the left.
