### ISSUE TITLE
First use modal for flagging

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#73]
@tladesignz When someone flags an item for the first time, we provide them with an informational modal/alert telling them what flagging does. A user will only see this one time.

[ic_flag-color.svg.zip](https://github.com/OpenArchive/openarchive-ios/files/3060381/ic_flag-color.svg.zip)

![OA-Preview-Flag](https://user-images.githubusercontent.com/1434597/55824026-a03fb700-5ac8-11e9-9d70-5d7fbc0581ef.png)

**Comment by kckthx** [comment]
Sorry @tladesignz but could we change this flag to (E9BD07) also?
