### ISSUE TITLE
sharing from camera app via share extension deletes proejct in OASave

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/openarchive-ios#75]
1) open camera
2) tap on thumbnail from existing photo
3) in photo view, tap share icon
4) select SAVE
5) select an existing project, tap import
6) project disappears from the list, but you do see successful "import" noification
7) open SAVE app, and project will be gone

**Comment by n8fr8** [comment]
doesn't happen if I create a "new project" in step 5 instead of selecting an existing one

**Comment by tladesignz** [comment]
@n8fr8, @foundscapes, @cstiens Please note:

I can confirm this problem, and am working on it.

This is a problem with YapDatabase running in a multi-process environment (main app and share extension) and not behaving as expected while doing so. Unfortunately, the docs aren't very helpful. I need to investigate further.

If you have troubles importing stuff via share extension and then not seeing it in the app as long as you don't restart it - don't create any more issues!

**Comment by tladesignz** [comment]
Ooh man. This one was really annoying.
