### ISSUE TITLE
consider deleting local copy once uploaded

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/openarchive-ios#76]
after using SAVE for a bit, it already used up 1.9GB of storage. I had imported a clip multiple times that was quite large. Over time, as people really use the app, we need a way to not keep duplicate copies of media files inside the app.

Some ideas include:
- not importing the same media files multiple times. Detect if it is the same, and re-use it
- once a file is uploaded to the server, remove the copy inside of SAVE

**Comment by n8fr8** [comment]
just to clarify, none of this will impact the original file the user has in the camera roll

**Comment by foundscapes** [comment]
Yes, this is why having a picker that shows media that was already uploaded would be helpful, but if that's not possible, I like @n8fr8 's ideas.

- is there an auto-detect that can use the first imported file?
- auto-remove from in-app would be great too

**Comment by foundscapes** [comment]
Could we have a global setting to allow people to auto-delete after upload?

**Comment by foundscapes** [comment]
Likely better not to make a setting but just implement.

**Comment by cstiens** [comment]
> once a file is uploaded to the server, remove the copy inside of SAVE

In this case, @n8fr8 if the copy is deleted and the user wants to view the media they've uploaded, will it look bad in full screen. I know we said we could keep thumbnails. But in the single view of a piece of media, it seems we would have a very low quality image. Is that right? We've been thinking about showing photos and videos larger after they've been sent to the server #78. That's why we're curious.

**Comment by n8fr8** [comment]
Maybe we keep a small thumbnail and large preview copy. The goal would be < 1MB per entry retained in the local app.

Honestly, this is really an issue related to medium/large video files mostly, and not photos, but the behavior should be consistent.

We could also, since we know the path on the server, offer the option to view/load the full image, audio, video file streamed from the server. This is what we would need to do if we wanted to support playback of larger video and audio files in the app.

**Comment by n8fr8** [comment]
On that least point, remember, the point of SAVE isn't to be a general purpose media gallery app, so we need to proceed with caution.

**Comment by n8fr8** [comment]
- delete app's local copy of full media file once upload is successful
- save thumbnail for display as icon and in detail view
- store path to copy on server

- optional: allow "streaming" view of full media from server path over webdav

**Comment by tladesignz** [comment]
> - delete app's local copy of full media file once upload is successful
> - save thumbnail for display as icon and in detail view
> - store path to copy on server

Ok, I implemented that.

However, what this whole issue brings up for me is: What for are we actually storing all the stuff anyway? If it's just fire-and-forget, why all the fancy project organization and upload history? Currently, the user can't do anything with it, besides copy-pasting some text they entered or deleting the assets or projects again.

Of course that's not important for a first version right now, but I'd argue we should keep an eye on this and see how the users are actually using it and what they will demand.

> - optional: allow "streaming" view of full media from server path over webdav

Didn't implement, as currently, there is no "watch the original file" feature implemented, anyway. One can just look at the thumbnail.
