### ISSUE TITLE
If Editing Upload Manager, All Uploads Should Pause

### ISSUE THREAD

**Issue by kckthx** [OpenArchive/openarchive-ios#79]
When editing the uploads in the upload manager, all uploads should pause so there is time to edit them. If the user has great internet connection it is nearly impossible to go through and cancel or re-order uploads. Feels like a race against the clock. 

So once the "Edit" state is reached, all uploads should pause, and will resume after editing.

![OA_upload-manager-uploading](https://user-images.githubusercontent.com/36669955/56138280-34dc6600-5f5c-11e9-8383-f9a95b97e03e.png)

**Comment by foundscapes** [comment]
@tladesignz 
Test Flight version 19
Phone: iphone xr ios 12.2 on wifi only
When I add media to project, hit upload then edit, all files still upload / not pausing when in edit mode
