### ISSUE TITLE
Updates to the Upload Manager

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#81]
- [ ] Remove 'Edit' and add grab bar action for moving items on main screen
- [x] Add file size to each item

**Comment by kckthx** [comment]
![OA_upload-manager-noedit](https://user-images.githubusercontent.com/36669955/56366924-cbf22980-61b9-11e9-9a36-6e08d429ee77.png)

**Comment by tladesignz** [comment]
I added the file size, as that was really needed.
However, the way, how moving items around works, is non-negotiable.
That's how Apple provides the interfaces, and that's how Apple wants it to be system-wide.

The `UITableViewController` has an "editing mode", where you can drag rows around. In editing mode, you cannot swipe-to-delete.
We can switch on the editing mode always, but then a white-minus-on-red-disc icon is showing on the left, too, to support deleting while in editing mode.

Besides that: I like the trash icon, unfortunately, that's not system-provided. Please provide, if you want that, and remind the set pixel size in the SVG! (should be 24 x 24 pixel)

**Comment by kckthx** [comment]
hey @tladesignz what is a system app instance of this? I know you're right and it exists and I've seen it, but the only ones I can think of right now (mail, messages, photos) are 'Select' > select the items > action bar shows at the bottom and delete is an option.

But i _know_ i've run into that instance of edit with the white disc and can't remember where.

**Comment by tladesignz** [comment]
Settings -> General -> Language & Region -> Edit
