### ISSUE TITLE
If we have location for an image, it should show in the info view of a single image

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#83]
@tladesignz @n8fr8 If we have location information for a photo or video, it should display in the information view of a single item. Any issue with implementing this?

**Comment by tladesignz** [comment]
You mean, if any location information is encoded in the photo/video itself, the app should automatically use that as location meta information?

Should it try to resolve GPS coordinates to addresses, also?


It seems, the information can be retrieved, when imported via picker:
https://stackoverflow.com/questions/26760410/extract-gps-data-from-photo

Not sure about share extension import.

**Comment by tladesignz** [comment]
Uuups. I got a little carried away, when I stumbled upon `PHAsset.location` again in the documentation. It's implemented now. :-)

**Comment by foundscapes** [comment]
Do we really want precise locations/addresses added automatically? This seems like a bad idea, especially when sending to the IA. Can we just have city/state/region instead? @tladesignz

**Comment by tladesignz** [comment]
Of course the user can always edit it.

What, if the user wants precise information added? How do you want to handle that?

**Comment by n8fr8** [comment]
I think this is just showing what is already there inside the photo or video. The phone camera app camera encodes this. If it is there, we should let them know.

**Comment by tladesignz** [comment]
Oh, yeah. Very true. That information is in the EXIF GPS header.
Anybody who's interested can take that coordinate and let it run through a "reverse geocoding" service by themselves.

I guess, we need some advanced scrubbing features in the next release.

**Comment by foundscapes** [comment]
Right but making it that explicit without people knowing seems unsafe.

**Comment by tladesignz** [comment]
You mean it's safer to hide it from them, so they leak very precise positioning information without them knowing?

**Comment by foundscapes** [comment]
It's not hiding it, it's just not making it as accessible.

**Comment by n8fr8** [comment]
We could just add a one time info screen saying something like:

"Your photo and video files may contain extra information (EXIF data) about your location and device. If this is a problem, you can disable this in your camera or phone settings. SAVE does not modify or clean any media you add."

**Comment by foundscapes** [comment]
Sure. The reason we wanted it to auto-populate location was primarily for field workers uploading large numbers of files, if it's easy to just have city/state instead, can we do that instead too?
