### ISSUE TITLE
Update language on edit media screen

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/openarchive-ios#87]
1)  Keep: Who is here? Separate names with commas.
2) Instead of “no location”change to: Where is this location? of populate with media location (if there is one, per ticket #83)
     a) Also needs to be same size/font in italics to match other fields
3) Instead of “notes” write: Add notes or tags here

**Comment by foundscapes** [comment]
Is this in the most recent version (17)? Changes aren't showing yet.

**Comment by tladesignz** [comment]
Nope. That is from last Friday. Next build will arrive eventually, please be patient.

**Comment by foundscapes** [comment]
Ok, just checking, thanks!
