### ISSUE TITLE
On-boarding Screens

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/openarchive-ios#88]
Content (needs editing) + design:

Screen One: 
Share: import all types of media: photos, video, audio, and text to Save

Screen Two: 
Archive: send your media to the archive of your choice, either private or public at the IA

Screen Three: 
Verify: use proofmode to collect sensor data that corroborates metadata and notarize your media before upload (@n8fr8 to work on language here so it's accurate)

Screen Four:
Encrypt: ensure your media is safe by encrypting your server or sending it to a secure server of your choice

**Comment by foundscapes** [comment]
To show up only on the first time when opening. Final Language for on-boarding screens @cstiens would it be hard to find icons or just have the logo or nothing for design?

**Screen one (Welcome screen):**
Design: name/logo w/ tagline under "Secure Mobile Media Preservation"
Text: Save All The Things! "Get Started" button on lower right (takes you to next on-boarding screen)

**Screen two:**
Design: share icon? https://www.flaticon.com/free-icon/share_149722#term=share&page=1&position=32
Text: Share: Connect to public or private spaces to safeguard your media.

**Screen three:**
Design: server stack w/ cloud? floppy?
Text: Archive: Build contextualized collections for easy long-term preservation and access.

**Screen Four:** need yr help w/ this one @n8fr8 -  let's discuss
Design: checkmark icon
Verify:  ...to more easily authenticate content. 

**Screen Five:**
Design: Lock icon
Encrypt: Protect your media from unauthorized access by encrypting your server.

**Comment by n8fr8** [comment]
"Adds extra metadata to help with chain of custody and verification workflows"

**Comment by foundscapes** [comment]
Design for flow: have dots at bottom showing how many screens there are (after first screen w/ linked text "Get Started")

**Comment by cstiens** [comment]
This is a line of copy we use in ProofMode: 
ProofMode captures information that makes your media more trustworthy.

We could use 'verifiable' in place of 'trustworthy'

**Comment by foundscapes** [comment]
**Final Language:** (@kckthx to add UI)

(Welcome screen):
Name/logo 
By OpenArchive
_Secure Mobile Media Preservation_ (italics)
Save All The Things! 
"Get Started" button on lower right (takes you to next on-boarding screen)
 
 
**Save to a safe place.**
Connect to a secure server or the internet archive to upload photos and videos from your phone.

**Stay organized.** 
Organize your media into projects.

**Store the facts.**
Capture notes, location and people with each piece of media.

**Ensure authenticity.**
Include your credentials while Save adds extra metadata to help with chain of custody and verification workflows.

**Comment by kckthx** [comment]
Here are screens and flow. Also attached are the demo phone screens as pngs for each step.

![OA-UX-Implementation_v1](https://user-images.githubusercontent.com/36669955/58044012-57860f80-7b04-11e9-8475-3f95570e5ce0.jpg)
[screen pngs.zip](https://github.com/OpenArchive/openarchive-ios/files/3199280/screen.pngs.zip)

**Comment by kckthx** [comment]
![save-logo](https://user-images.githubusercontent.com/36669955/58044165-bc416a00-7b04-11e9-99d8-002e3fcab3e2.png)
also here is the png of the Save logo for screen 1 top left corner

**Comment by foundscapes** [comment]
Looks great @kckthx!

**Comment by tladesignz** [comment]
@kckthx Can you do the "loading screen" (aka. the `LaunchScreen` in iOS speak) as a 1024 x 1024 px PNG *and* SVG? (Want to try out both.)

Also, will you provide the screenshots seen in the scenes? 

Please remember that we're running on devices as diverse as from iPhone 5s to iPad Pro 13"! So don't cut the images but instead be prepared that the most important information needs to be visible in the top left quarter, because other parts could be outside the screen estate.

**Comment by kckthx** [comment]
gotcha @tladesignz here are the full screens
[Full-Phones.zip](https://github.com/OpenArchive/openarchive-ios/files/3207718/Full-Phones.zip)
And the launch screen as 1024x1024
[Launch-screen.zip](https://github.com/OpenArchive/openarchive-ios/files/3207720/Launch-screen.zip)

**Comment by tladesignz** [comment]
@kckthx Sorry, I also need that > as an image. I thought we already had that, but couldn't find it anymore. SVG, please! 24 x 24 px should do it.

**Comment by kckthx** [comment]
ok, here it is in the asset repo https://github.com/OpenArchive/openarchive-assets/blob/master/icons/next.svg

Do you need it in white also, or can you do that since it's an SVG?
@tladesignz

**Comment by foundscapes** [comment]
@tladesignz we have to tape many times on first screen "get started" before it takes you to second screen

**Comment by foundscapes** [comment]
Still lagging when touching "get started" on version 23

**Comment by foundscapes** [comment]
"Done" in upper right is small/hard to see - perhaps put "continue to save" in lower right - same size as "get started"
@kckthx @tladesignz

**Comment by tladesignz** [comment]
@foundscapes No space in lower right.

**Comment by tladesignz** [comment]
Regarding the launch screen:
I spent about 1.5 hours on this now. It seems, iOS actively ignores some images based on their content.
I can use some icons and a TV test picture, but not some logos and other images. Not sure what the rules are exactly. I guess it's a combination of size and color use.

I'll leave it as is, now.
In the meantime, I heavily recommend, you study Apple's guidelines regarding the launch screen:

https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/launch-screen/

I especially want to make you aware of this:

> Don’t advertise. The launch screen isn’t a branding opportunity. Don’t design an entry experience that looks like a splash screen or an "About" window. Don’t include logos or other branding elements unless they’re a static part of your app’s first screen.

From here on, I'll use this issue to track the state of the onboarding tutorial. For launch screen related stuff, please open another issue.

**Comment by kckthx** [comment]
all fonts should be montserrat

**Comment by tladesignz** [comment]
@kckthx: Next time, please reopen, so comments like these don't get lost on open issue review!
