### ISSUE TITLE
New items set to "uploading" without review

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/openarchive-ios#93]
Build 0.2.0 (16)

1) Add one image from camera roll
2) Click Levels icon, Preview and Upload that image
3) Upload seems to start but no change in progres
4) Return to app main screen
5) Add two more images to camera roll
6) These are seemingly immediately set to upload state - status reads "0 of 3" uploading, even though only the first item was sent to upload
7) check upload manager, and only 1 item still there, and still stuck

![image](https://user-images.githubusercontent.com/30851/56702986-d25e3500-66d4-11e9-9f81-01d44540cdb5.png)
![image](https://user-images.githubusercontent.com/30851/56702996-ddb16080-66d4-11e9-84a5-db2ce80a0487.png)

**Comment by n8fr8** [comment]
This might be related to #80

**Comment by tladesignz** [comment]
Is unrelated. I just forgot to store the closing of a collection.
This was unfortunately covered by a piece of code which checked the closed state of a collection during upload. So users saw this only, when the upload was slow... 🤪

**Comment by tladesignz** [comment]
Thanks for catching and the very nice bug report!
