### ISSUE TITLE
Little/no indicator during slow import of large file

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/openarchive-ios#94]
I imported an 18 minute + video file, which I assume is quite large. It took at least 30 seconds for it to show up in the SAVE Project. The only indicator something was happening was a spinning icon up in the iOS status bar near the network indicator, and a little flickering of the other thumbnails in the project.

We should probably have some sort of "Please wait" or "Importing..." status bar.

**Comment by cstiens** [comment]
@n8fr8 To clarify, after you selected the video from the camera roll, nothing showed up on the Save home screen? Not even a thumbnail?

**Comment by tladesignz** [comment]
The confusion could be, because I fiddled with this, already. It now imports audio/video in the background while already creating the asset and a thumbnail. It won't start uploading, however, until the import is fully finished.

**Comment by tladesignz** [comment]
I think, this is dealt with properly, already, with the way it is since a few month: It will show up immediately, user can handle it as needed and it will be uploaded, as soon as it's fully encoded.

I'll close this issue, therefore. Feel free to reopen, when you find a hair in the soup. ;-)
