### ISSUE TITLE
'Settings' changed to 'Menu'

### ISSUE THREAD

**Issue by kckthx** [OpenArchive/openarchive-ios#96]
I know we've been round and round about the name of the settings screen, but I think we've finally landed on what works. 

Here is the new layout for 'Menu' with a division between server specific and global settings.
![OA-Menu](https://user-images.githubusercontent.com/36669955/56769716-a5af2980-6777-11e9-8940-19b1ee8ef65b.png)

The 'Data Usage' tab will take you to a place to select whether or not to upload only over wifi #89 . This will also be an option in initial onboarding, but we haven't gotten to designing all of that yet. 
![OA-data-usage](https://user-images.githubusercontent.com/36669955/56769735-b790cc80-6777-11e9-9938-56e4ca652917.png)

@cstiens @tladesignz @n8fr8 @foundscapes

**Comment by kckthx** [comment]
@cr this is in #95
I made this ticket before I saw the already opened one

**Comment by kckthx** [comment]
@tladesignz there is a workflow for the server and profile view from the menu in issue #70 

We would also like to implement having no lines on menu items.

**Comment by tladesignz** [comment]
> @tladesignz there is a workflow for the server and profile view from the menu in issue #70

Thanks!

> We would also like to implement having no lines on menu items.

Fixed with commit 661ff1cee37a2d6a4795f09560f157c4bb31415c.
