### ISSUE TITLE
Workflow for adding/uploading from within the app

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#98]
@tladesignz This may be in another ticket, but we're unable to find it.

When a user opens the app and taps the '+' icon to add/upload media, the next steps should follow:
* Camera roll multi-select (which we have)
* Preview
* User taps upload from the preview view
* Home with items uploading

Let us know if you have questions or need a mockup.

**Comment by foundscapes** [comment]
I know you referenced / closed the bulk editing ticket, so would we need UI for editing from within the preview screen to implement? @cstiens @tladesignz

**Comment by tladesignz** [comment]
@foundscapes No worries. No UI changes, just a change in the chain of scenes.
