### ISSUE TITLE
Project folders on the server

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#99]
@n8fr8 @tladesignz Is every project on a server shared between everyone who has access to the server regardless of who created it?

Kaci and I have both logged in to the same Guardian server, but with 2 different accounts. We see different folders that we can browse on the server.

**Comment by tladesignz** [comment]
That depends on the actual WebDAV server software used and its configuration.
Nextcloud has a sharing feature. Maybe that's what you can use to achieve what you want?

**Comment by cstiens** [comment]
Ok thanks. So, in the UI, we can't say it will behave one way or another because we don't have control over that.

**Comment by tladesignz** [comment]
> because we don't have control over that.

Exactly. Not our department.
